### ISSUE TITLE
Sound is kinda "wobbly"

### ISSUE THREAD

**Issue by Mawarii** [Spark-Devices/device-xiaomi-davinci#2]
I am sorry for the bad description but I have no idea how to describe this issue.
If I watch a video on youtube or listen to music the sound is not on the same level even if I am not changing the volume.
So if there is just a little sound its normal, but if there is much more sound (like 2 people are talking at the same time or someone is screaming) the volume level goes up without changing anything.

I can try to record it for a better understanding but I don't know if that'll work.

**Comment by Ashishzzzboop** [comment]
Just disable volume leveller in moto Dolby by going to dolby change to music or any other edit and disable levller
